version: '3.8'

services:
  web:
    build: .
    command: bash -c "
      python ./src/manage.py migrate &&
      python ./src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src/cars
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cars_db
      - POSTGRES_USER=netguru
      - POSTGRES_PASSWORD=Netguru!

volumes:
  postgres_data: